{
 "title": "Linux服务器主机监控大盘",
 "tags": [
  "linux",
  "node",
  "服务器监控"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "系统总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU使用率 {{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "内存使用率 {{instance}}"
    }
   ]
  },
  { "title": "磁盘IO & 网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "磁盘读写流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "磁盘读 {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "磁盘写 {{device}}"
    }
   ]
  },
  {
   "title": "网卡进出流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])",
     "legendFormat": "网卡入流量 {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "网卡出流量 {{device}}"
    }
   ]
  }
 ]
}